
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        projects:
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true